services:
  naoRobotAPI:
    build: 
      context: ./naoRobotAPI
      dockerfile: Dockerfile
    command: python server.py
    image: jperdek/nao-robot-api
    container_name: naoRobotAPI
    env_file: .env
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      HOST_PORT: ${HOST_PORT:-1234}
      HOST_IP: ${HOST_IP:-127.0.0.1}
      NAO_PORT: ${NAO_PORT:-9559}
      NAO_IP: host.docker.internal
      FLASK_ENV: development
    networks:
      - buildernet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  skeletonFinderAPI:
    build: 
      context: ./skeletonFinderAPI
      dockerfile: Dockerfile
    command: python server.py
    image: jperdek/skeleton-finder-api
    container_name: skeletonFinderAPI
    env_file: .env
    ports:
      - "127.0.0.1:6001:6001"
    environment:
      FLASK_ENV: development
    volumes:
      - /home/noetic/Pictures:/images:ro
    networks:
      - buildernet

  translatorArmsAPI:
    build:
      context: ./translator_arms
      dockerfile: Dockerfile
    command: python nao_pose_service.py
    image: jperdek/translator-arms-api
    container_name: translatorArmsAPI
    env_file: .env
    ports:
      - "127.0.0.1:7000:7000"
    environment:
      FLASK_ENV: development 
    volumes:
      - /home/noetic/Pictures:/home/noetic/Pictures
    depends_on:
      - naoRobotAPI
      - skeletonFinderAPI
    networks:
      - buildernet

networks:
  buildernet:
    driver: "bridge"
