services:
    naoRobotAPI:
        build: 
            context: ./naoRobotAPI
            dockerfile: Dockerfile
        command: python a.py
        image: jperdek/nao-robot-api
        container_name: naoRobotAPI
        env_file: .env
        environment:
            HOST_PORT: ${HOST_PORT:-1234}
            HOST_IP: ${HOST_IP:-127.0.0.1}
            NAO_PORT: ${NAO_PORT:-9559}
            NAO_IP: ${NAO_IP:-host.docker.internal}
            FLASK_ENV: development
        networks:
            - buildernet
    choregraphe288:
        image: dogarty33/choreographe-setup:2.8.8
        ports:
            - "127.0.0.1:9559:9559"
        networks:
            - buildernet
networks:
    buildernet:
        driver: "bridge"
        